ServerEvents.recipes(event => {

	event.blasting('bigreactors:anglesite_crystal', 'bigreactors:anglesite_ore')
	event.blasting('bigreactors:benitoite_crystal', 'bigreactors:benitoite_ore')
	event.blasting('mekanism:ingot_tin', '#forge:ores/tin') 
	event.blasting('mekanism:ingot_osmium', '#forge:ores/osmium')
	event.blasting('mekanism:ingot_lead', '#forge:ores/lead')
	event.blasting('mekanism:ingot_uranium', 'mekanism:uranium_ore') 
	event.blasting('mekanism:fluorite_gem', 'mekanism:fluorite_ore') 
	event.blasting('thermal:apatite', 'thermal:apatite_ore') 
	event.blasting('thermal:cinnabar', 'thermal:cinnabar_ore') 
	event.blasting('thermal:sulfur', 'thermal:sulfur_ore') 
	event.blasting('thermal:sapphire', '#forge:ores/sapphire') 
	event.blasting('thermal:ruby', '#forge:ores/ruby')
	event.blasting('tconstruct:cobalt_ingot', 'astro_rise:crushed_raw_cobalt')
	event.blasting('astro_rise:ingot_aerolyte', 'astro_rise:mercury_aerolyte_ore')
	event.blasting('astro_rise:ingot_aerolyte', 'astro_rise:crushed_raw_aerolyte')
	event.blasting('platinum_mod:platinum', 'create:crushed_raw_platinum')

})