ServerEvents.recipes(event => {

	event.blasting('bigreactors:anglesite_crystal', 'bigreactors:anglesite_ore')
	event.blasting('bigreactors:benitoite_crystal', 'bigreactors:benitoite_ore')
	event.blasting('mekanism:ingot_tin', 'mekanism:tin_ore') 
	event.blasting('mekanism:ingot_tin', 'mekanism:deepslate_tin_ore') 
	event.blasting('mekanism:ingot_osmium', 'mekanism:osmium_ore') 
	event.blasting('mekanism:ingot_osmium', 'mekanism:deepslate_osmium_ore') 
	event.blasting('mekanism:ingot_osmium', 'mekanismaaa:moon_osmium_ore') 
	event.blasting('mekanism:ingot_lead', 'mekanism:lead_ore') 
	event.blasting('mekanism:ingot_lead', 'mekanism:deepslate_lead_ore') 
	event.blasting('mekanism:ingot_uranium', 'mekanism:uranium_ore') 
	event.blasting('mekanism:fluorite_gem', 'mekanism:fluorite_ore') 
	event.blasting('thermal:apatite', 'thermal:apatite_ore') 
	event.blasting('thermal:cinnabar', 'thermal:cinnabar_ore') 
	event.blasting('thermal:niter', 'thermal:niter_ore') 
	event.blasting('thermal:sulfur', 'thermal:sulfur_ore') 
	event.blasting('thermal:ingot_silver', 'thermal:silver_ore') 
	event.blasting('thermal:ingot_silver', 'thermal:deepslate_silver_ore') 
	event.blasting('thermal:ingot_nickel', 'thermal:nickel_ore') 
	event.blasting('thermal:ingot_nickel', 'thermal:deepslate_nickel_ore') 
	event.blasting('thermal:sapphire', 'thermal:sapphire_ore') 
	event.blasting('thermal:sapphire', 'thermal:deepslate_sapphire_ore') 
	event.blasting('thermal:ruby', 'thermal:ruby_ore') 
	event.blasting('thermal:ruby', 'thermal:deepslate_ruby_ore') 
})