ServerEvents.recipes(event => {

	event.blasting('bigreactors:anglesite_crystal', 'bigreactors:anglesite_ore')
	event.blasting('bigreactors:benitoite_crystal', 'bigreactors:benitoite_ore')
	event.blasting('mekanism:ingot_tin', '#forge:ores/tin') 
	event.blasting('mekanism:ingot_osmium', '#forge:ores/osmium')
	event.blasting('mekanism:ingot_lead', '#forge:ores/lead')
	event.blasting('mekanism:ingot_uranium', 'mekanism:uranium_ore') 
	event.blasting('mekanism:fluorite_gem', 'mekanism:fluorite_ore') 
	event.blasting('thermal:apatite', 'thermal:apatite_ore') 
	event.blasting('thermal:cinnabar', 'thermal:cinnabar_ore') 
	event.blasting('thermal:sulfur', 'thermal:sulfur_ore') 
	event.blasting('thermal:sapphire', '#forge:ores/sapphire') 
	event.blasting('thermal:ruby', '#forge:ores/ruby')
	event.blasting('tconstruct:cobalt_ingot', 'astro_rise:crushed_raw_cobalt')
	event.blasting('astro_rise:ingot_aerolyte', 'astro_rise:mercury_aerolyte_ore')
	event.blasting('astro_rise:ingot_aerolyte', 'astro_rise:crushed_raw_aerolyte')
	event.blasting('platinum_mod:platinum', 'create:crushed_raw_platinum')
	event.blasting('create:zinc_ingot', 'astro_rise:dust_zinc')
	event.blasting('simplemetals_aluminum:aluminum_ingot', 'astro_rise:dust_aluminum')
	event.blasting('platinum_mod:platinum', 'astro_rise:dust_platinum')
	event.blasting('ad_astra:desh_ingot', 'astro_rise:dust_desh')
	event.blasting('ad_astra:ostrum_ingot', 'astro_rise:dust_ostrum')
	event.blasting('ad_astra:calorite_ingot', 'astro_rise:dust_calorite')
	event.blasting('astro_rise:ingot_aerolyte', 'astro_rise:dust_aerolyte')
	event.blasting('ad_astra:ice_shard', 'astro_rise:dust_ice_shard')
	event.blasting('minecraft:ender_pearl', 'thermal:ender_pearl_dust')
	event.blasting('enderio:soularium_ingot', 'enderio:soul_powder')
	event.blasting('minecraft:obsidian', 'create:powdered_obsidian')

})