ServerEvents.recipes(event => {

	event.smelting('bigreactors:anglesite_crystal', 'bigreactors:anglesite_ore')
	event.smelting('bigreactors:benitoite_crystal', 'bigreactors:benitoite_ore')
	event.smelting('mekanism:ingot_tin', '#forge:ores/tin')  
	event.smelting('mekanism:ingot_osmium', '#forge:ores/osmium')
	event.smelting('mekanism:ingot_lead', '#forge:ores/lead')
	event.smelting('mekanism:ingot_uranium', 'mekanism:uranium_ore') 
	event.smelting('mekanism:fluorite_gem', 'mekanism:fluorite_ore') 
	event.smelting('thermal:apatite', 'thermal:apatite_ore') 
	event.smelting('thermal:cinnabar', 'thermal:cinnabar_ore') 
	event.smelting('thermal:sulfur', 'thermal:sulfur_ore') 
	event.smelting('thermal:sapphire', '#forge:ores/sapphire') 
	event.smelting('thermal:ruby', '#forge:ores/ruby')
	event.smelting('tconstruct:cobalt_ingot', 'tconstruct:cobalt_ore')
})