ServerEvents.recipes(event => {

	event.recipes.createoreexcavation.vein('{"text": "Lava"}', 'minecraft:lava_bucket')
		.placement(500, 128, 64632489)
		.veinSize(5, 8)
		.id('astro_rise:lava_vein')
		.alwaysInfinite()
		.biomeWhitelist('astro_rise:has_lava_vein')

	event.recipes.createoreexcavation.vein('{"text": "Raw Cobalt"}', 'tconstruct:raw_cobalt')
	    .placement(800, 256, 64825185)
	    .veinSize(5, 8)
	    .id('astro_rise:cobalt_vein')
	    .alwaysInfinite()
	    .biomeWhitelist('forge:is_hot/nether')

	event.recipes.createoreexcavation.vein('{"text": "Raw Silver"}', 'thermal:raw_silver')
		.placement(400, 128, 48291735)
		.veinSize(5, 8)
		.id('astro_rise:silver_vein')
	    .alwaysInfinite()
	    .biomeWhitelist('minecraft:is_overworld')

	event.recipes.createoreexcavation.vein('{"text": "Raw Nickel"}', 'thermal:raw_nickel')
		.placement(400, 128, 19384726)
		.veinSize(5, 8)
		.id('astro_rise:nickel_vein')
	    .alwaysInfinite()
	    .biomeWhitelist('minecraft:is_overworld')

	event.recipes.createoreexcavation.vein('{"text": "Raw Tin"}', 'mekanism:raw_tin')
		.placement(400, 128, 57629018)
		.veinSize(5, 8)
		.id('astro_rise:tin_vein')
	    .alwaysInfinite()
	    .biomeWhitelist('minecraft:is_overworld')

	event.recipes.createoreexcavation.vein('{"text": "Raw Lead"}', 'mekanism:raw_lead')
		.placement(400, 128, 95017263)
		.veinSize(5, 8)
		.id('astro_rise:lead_vein')
	    .alwaysInfinite()
	    .biomeWhitelist('minecraft:is_overworld')

	event.recipes.createoreexcavation.vein('{"text": "Raw Osmium"}', 'mekanism:raw_osmium')
		.placement(400, 128, 86423109)
		.veinSize(5, 8)
		.id('astro_rise:osmium_vein')
	    .alwaysInfinite()
	    .biomeWhitelist('astro_rise:has_moon_vein')

	event.recipes.createoreexcavation.vein('{"text": "Fluorite"}', 'mekanism:fluorite_gem')
		.placement(800, 256, 32847610)
		.veinSize(4, 7)
		.id('astro_rise:fluorite_vein')
	    .alwaysInfinite()
	    .biomeWhitelist('astro_rise:has_sculk_vein')

	event.recipes.createoreexcavation.vein('{"text": "Raw Uranium"}', 'mekanism:raw_uranium')
		.placement(800, 256, 70159284)
		.veinSize(4, 7)
		.id('astro_rise:uranium_vein')
	    .alwaysInfinite()
	    .biomeWhitelist('astro_rise:has_blooming_vein')

	event.recipes.createoreexcavation.vein('{"text": "Anglesite (PbS04)"}', 'bigreactors:anglesite_crystal')
		.placement(400, 128, 89152849)
		.veinSize(3, 5)
		.id('astro_rise:anglesite_vein')
	    .alwaysInfinite()
	    .biomeWhitelist('minecraft:is_end')

	event.recipes.createoreexcavation.vein('{"text": "Benitoite (BaTiSi309)"}', 'bigreactors:benitoite_crystal')
		.placement(400, 128, 91159842)
		.veinSize(3, 5)
		.id('astro_rise:benitoite_vein')
	    .alwaysInfinite()
	    .biomeWhitelist('minecraft:is_nether')

	event.recipes.createoreexcavation.vein('{"text": "Apatite"}', 'thermal:apatite')
		.placement(200, 96, 61483097)
		.veinSize(3, 5)
		.id('astro_rise:apatite_vein')
	    .alwaysInfinite()
	    .biomeWhitelist('minecraft:is_end')

	event.recipes.createoreexcavation.vein('{"text": "Cinnabar"}', 'thermal:cinnabar')
		.placement(200, 96, 28746501)
		.veinSize(3, 5)
		.id('astro_rise:cinnabar_vein')
	    .alwaysInfinite()
	    .biomeWhitelist('minecraft:is_nether')

	event.recipes.createoreexcavation.vein('{"text": "Ruby"}', 'thermal:ruby')
		.placement(600, 196, 43098125)
		.veinSize(5, 8)
		.id('astro_rise:ruby_vein')
	    .alwaysInfinite()
	    .biomeWhitelist('minecraft:is_mountain')

	event.recipes.createoreexcavation.vein('{"text": "Sapphire"}', 'thermal:sapphire')
		.placement(600, 196, 75960384)
		.veinSize(5, 8)
		.id('astro_rise:sapphire_vein')
	    .alwaysInfinite()
	    .biomeWhitelist('minecraft:is_mountain')

	event.recipes.createoreexcavation.vein('{"text": "Niter"}', 'thermal:niter')
		.placement(800, 256, 10649287)
		.veinSize(2, 6)
		.id('astro_rise:niter_vein')
	    .alwaysInfinite()
	    .biomeWhitelist('astro_rise:has_venus_vein')

	event.recipes.createoreexcavation.vein('{"text": "Sulfur"}', 'thermal:sulfur')
		.placement(800, 256, 89271536)
		.veinSize(2, 6)
		.id('astro_rise:sulfur_vein')
	    .alwaysInfinite()
	    .biomeWhitelist('astro_rise:has_mercury_vein')

	event.recipes.createoreexcavation.vein('{"text": "Raw Desh"}', 'ad_astra:raw_desh')
		.placement(400, 128, 54362819)
		.veinSize(3, 5)
		.id('astro_rise:desh_vein')
	    .alwaysInfinite()
	    .biomeWhitelist('astro_rise:has_moon_vein')

	event.recipes.createoreexcavation.vein('{"text": "Ice Shard"}', 'ad_astra:ice_shard')
		.placement(400, 128, 27190485)
		.veinSize(3, 5)
		.id('astro_rise:ice_shard_vein')
	    .alwaysInfinite()
	    .biomeWhitelist('astro_rise:has_moon_vein')

	event.recipes.createoreexcavation.vein('{"text": "Raw Ostrum"}', 'ad_astra:raw_ostrum')
		.placement(400, 128, 63812049)
		.veinSize(3, 5)
		.id('astro_rise:ostrum_vein')
	    .alwaysInfinite()
	    .biomeWhitelist('astro_rise:has_mars_vein')

	event.recipes.createoreexcavation.vein('{"text": "Raw Calorite"}', 'ad_astra:raw_calorite')
		.placement(400, 128, 80573421)
		.veinSize(3, 5)
		.id('astro_rise:calorite_vein')
	    .alwaysInfinite()
	    .biomeWhitelist('astro_rise:has_venus_vein')

})