ServerEvents.recipes(event => {

	event.remove({ id: 'createoreexcavation:ore_vein_type/nether_gold' })
	event.remove({ id: 'createoreexcavation:ore_vein_type/gold' })

	event.recipes.createoreexcavation.vein('{"text": "Raw Gold"}', 'minecraft:raw_gold')
		.placement(800, 256, 59423571)
		.veinSize(5, 8)
		.id('astro_rise:ore_vein_type/gold')
		.alwaysInfinite()
		.biomeWhitelist('astro_rise:has_gold_vein')

	event.remove({ id: 'createoreexcavation:ore_vein_type/netherite' })

	event.recipes.createoreexcavation.vein('{"text": "Ancient Debris"}', 'minecraft:ancient_debris')
		.placement(500, 128, 72624489)
		.veinSize(2, 4)
		.id('astro_rise:ore_vein_type/netherite')
		.alwaysInfinite()
		.biomeWhitelist('minecraft:is_nether')

	event.recipes.createoreexcavation.vein('{"text": "Lava"}', 'minecraft:lava_bucket')
		.placement(500, 128, 64632489)
		.veinSize(5, 8)
		.id('astro_rise:ore_vein_type/lava')
		.alwaysInfinite()
		.biomeWhitelist('astro_rise:has_lava_vein')

	event.recipes.createoreexcavation.vein('{"text": "Raw Cobalt"}', 'tconstruct:raw_cobalt')
	    .placement(800, 256, 64825185)
	    .veinSize(5, 8)
	    .id('astro_rise:ore_vein_type/cobalt')
	    .alwaysInfinite()
	    .biomeWhitelist('forge:is_hot/nether')

	event.recipes.createoreexcavation.vein('{"text": "Raw Silver"}', 'thermal:raw_silver')
		.placement(400, 128, 48291735)
		.veinSize(5, 8)
		.id('astro_rise:ore_vein_type/silver')
	    .alwaysInfinite()
	    .biomeWhitelist('minecraft:is_overworld')

	event.recipes.createoreexcavation.vein('{"text": "Raw Nickel"}', 'thermal:raw_nickel')
		.placement(400, 128, 19384726)
		.veinSize(5, 8)
		.id('astro_rise:ore_vein_type/nickel')
	    .alwaysInfinite()
	    .biomeWhitelist('minecraft:is_overworld')

	event.recipes.createoreexcavation.vein('{"text": "Raw Tin"}', 'mekanism:raw_tin')
		.placement(400, 128, 57629018)
		.veinSize(5, 8)
		.id('astro_rise:ore_vein_type/tin')
	    .alwaysInfinite()
	    .biomeWhitelist('minecraft:is_overworld')

	event.recipes.createoreexcavation.vein('{"text": "Raw Lead"}', 'mekanism:raw_lead')
		.placement(400, 128, 95017263)
		.veinSize(5, 8)
		.id('astro_rise:ore_vein_type/lead')
	    .alwaysInfinite()
	    .biomeWhitelist('minecraft:is_overworld')

	event.recipes.createoreexcavation.vein('{"text": "Raw Osmium"}', 'mekanism:raw_osmium')
		.placement(400, 128, 86423109)
		.veinSize(5, 8)
		.id('astro_rise:ore_vein_type/osmium')
	    .alwaysInfinite()
	    .biomeWhitelist('astro_rise:has_moon_vein')

	event.recipes.createoreexcavation.vein('{"text": "Fluorite"}', 'mekanism:fluorite_gem')
		.placement(800, 256, 32847610)
		.veinSize(4, 7)
		.id('astro_rise:ore_vein_type/fluorite')
	    .alwaysInfinite()
	    .biomeWhitelist('astro_rise:has_sculk_vein')

	event.recipes.createoreexcavation.vein('{"text": "Raw Uranium"}', 'mekanism:raw_uranium')
		.placement(800, 256, 70159284)
		.veinSize(4, 7)
		.id('astro_rise:ore_vein_type/uranium')
	    .alwaysInfinite()
	    .biomeWhitelist('astro_rise:has_blooming_vein')

	event.recipes.createoreexcavation.vein('{"text": "Raw Bauxite"}', 'simplemetals_aluminum:raw_aluminum')
		.placement(400, 128, 25159364)
		.veinSize(4, 7)
		.id('astro_rise:ore_vein_type/aluminum')
	    .alwaysInfinite()
	    .biomeWhitelist('minecraft:is_overworld')

	event.recipes.createoreexcavation.vein('{"text": "Raw Platinum"}', 'platinum_mod:raw_platinum')
		.placement(400, 256, 31159894)
		.veinSize(3, 5)
		.id('astro_rise:ore_vein_type/platinum')
	    .alwaysInfinite()
	    .biomeWhitelist('minecraft:is_overworld')

	event.recipes.createoreexcavation.vein('{"text": "Anglesite (PbS04)"}', 'bigreactors:anglesite_crystal')
		.placement(400, 128, 89152849)
		.veinSize(3, 5)
		.id('astro_rise:ore_vein_type/anglesite')
	    .alwaysInfinite()
	    .biomeWhitelist('minecraft:is_end')

	event.recipes.createoreexcavation.vein('{"text": "Benitoite (BaTiSi309)"}', 'bigreactors:benitoite_crystal')
		.placement(400, 128, 91159842)
		.veinSize(3, 5)
		.id('astro_rise:ore_vein_type/benitoite')
	    .alwaysInfinite()
	    .biomeWhitelist('minecraft:is_nether')

	event.recipes.createoreexcavation.vein('{"text": "Apatite"}', 'thermal:apatite')
		.placement(200, 96, 61483097)
		.veinSize(3, 5)
		.id('astro_rise:ore_vein_type/apatite')
	    .alwaysInfinite()
	    .biomeWhitelist('minecraft:is_end')

	event.recipes.createoreexcavation.vein('{"text": "Cinnabar"}', 'thermal:cinnabar')
		.placement(200, 96, 28746501)
		.veinSize(3, 5)
		.id('astro_rise:ore_vein_type/cinnabar')
	    .alwaysInfinite()
	    .biomeWhitelist('minecraft:is_nether')

	event.recipes.createoreexcavation.vein('{"text": "Ruby"}', 'thermal:ruby')
		.placement(600, 196, 43098125)
		.veinSize(5, 8)
		.id('astro_rise:ore_vein_type/ruby')
	    .alwaysInfinite()
	    .biomeWhitelist('minecraft:is_mountain')

	event.recipes.createoreexcavation.vein('{"text": "Sapphire"}', 'thermal:sapphire')
		.placement(600, 196, 75960384)
		.veinSize(5, 8)
		.id('astro_rise:ore_vein_type/sapphire')
	    .alwaysInfinite()
	    .biomeWhitelist('minecraft:is_mountain')

	event.recipes.createoreexcavation.vein('{"text": "Niter"}', 'thermal:niter')
		.placement(800, 256, 10649287)
		.veinSize(2, 6)
		.id('astro_rise:ore_vein_type/niter')
	    .alwaysInfinite()
	    .biomeWhitelist('astro_rise:has_venus_vein')

	event.recipes.createoreexcavation.vein('{"text": "Sulfur"}', 'thermal:sulfur')
		.placement(800, 256, 89271536)
		.veinSize(2, 6)
		.id('astro_rise:ore_vein_type/sulfur')
	    .alwaysInfinite()
	    .biomeWhitelist('astro_rise:has_mercury_vein')

	event.recipes.createoreexcavation.vein('{"text": "Raw Desh"}', 'ad_astra:raw_desh')
		.placement(400, 128, 54362819)
		.veinSize(3, 5)
		.id('astro_rise:ore_vein_type/desh')
	    .alwaysInfinite()
	    .biomeWhitelist('astro_rise:has_moon_vein')

	event.recipes.createoreexcavation.vein('{"text": "Ice Shard"}', 'ad_astra:ice_shard')
		.placement(400, 128, 27190485)
		.veinSize(3, 5)
		.id('astro_rise:ore_vein_type/ice_shard')
	    .alwaysInfinite()
	    .biomeWhitelist('astro_rise:has_moon_vein')

	event.recipes.createoreexcavation.vein('{"text": "Raw Ostrum"}', 'ad_astra:raw_ostrum')
		.placement(400, 128, 63812049)
		.veinSize(3, 5)
		.id('astro_rise:ore_vein_type/ostrum')
	    .alwaysInfinite()
	    .biomeWhitelist('astro_rise:has_mars_vein')

	event.recipes.createoreexcavation.vein('{"text": "Raw Calorite"}', 'ad_astra:raw_calorite')
		.placement(400, 128, 80573421)
		.veinSize(3, 5)
		.id('astro_rise:ore_vein_type/calorite')
	    .alwaysInfinite()
	    .biomeWhitelist('astro_rise:has_venus_vein')

	event.recipes.createoreexcavation.vein('{"text": "Raw Aerolyte"}', 'astro_rise:raw_aerolyte')
		.placement(400, 128, 80573421)
		.veinSize(3, 5)
		.id('astro_rise:ore_vein_type/aerolyte')
	    .alwaysInfinite()
	    .biomeWhitelist('astro_rise:has_mercury_vein')

})