ServerEvents.recipes(event => {

	event.remove({ output: /twilightforest:hollow_.*/ })

	// ores cleaning

	event.remove({ input: 'ad_astra:deepslate_desh_ore' })
	event.remove({ input: 'ad_astra:deepslate_ice_shard_ore' })
	event.remove({ input: 'ad_astra:mars_ice_shard_ore' })
	event.remove({ input: 'ad_astra:glacio_ice_shard_ore' })
	event.remove({ input: 'ad_astra:deepslate_ostrum_ore' })
	event.remove({ input: 'ad_astra:deepslate_calorite_ore' })
	event.remove({ input: 'mekanism:deepslate_uranium_ore' })
	event.remove({ output: 'mekanism:deepslate_uranium_ore' })
	event.remove({ input: 'mekanism:deepslate_fluorite_ore' })
	event.remove({ output: 'mekanism:deepslate_fluorite_ore' })
	event.remove({ input: 'mekanismaaa:glacio_fluorite_ore' })
	event.remove({ input: 'mekanismaaa:glacio_lead_ore' })
	event.remove({ input: 'mekanismaaa:glacio_osmium_ore' })
	event.remove({ input: 'mekanismaaa:glacio_uranium_ore' })
	event.remove({ input: 'mekanismaaa:glacio_tin_ore' })
	event.remove({ input: 'mekanismaaa:mars_fluorite_ore' })
	event.remove({ input: 'mekanismaaa:mars_uranium_ore' })
	event.remove({ input: 'mekanismaaa:mars_tin_ore' })
	event.remove({ input: 'mekanismaaa:mercury_lead_ore' })
	event.remove({ input: 'mekanismaaa:mercury_osmium_ore' })
	event.remove({ input: 'mekanismaaa:mercury_uranium_ore' })
	event.remove({ input: 'mekanismaaa:moon_tin_ore' })
	event.remove({ input: 'mekanismaaa:venus_fluorite_ore' })
	event.remove({ input: 'mekanismaaa:venus_lead_ore' })
	event.remove({ input: 'mekanismaaa:venus_uranium_ore' })
	event.remove({ input: 'thermal:deepslate_apatite_ore' })
	event.remove({ input: 'thermal:deepslate_cinnabar_ore' })
	event.remove({ input: 'thermal:deepslate_niter_ore' })
	event.remove({ input: 'thermal:deepslate_sulfur_ore' })
	event.remove({ input: 'deeperdarker:sculk_stone_redstone_ore' })
	event.remove({ input: 'deeperdarker:gloomslate_redstone_ore' })
})