JEIEvents.hideItems(event => {

	event.hide('ad_astra:deepslate_desh_ore')
	event.hide('ad_astra:deepslate_ice_shard_ore')
	event.hide('ad_astra:mars_ice_shard_ore')
	event.hide('ad_astra:glacio_ice_shard_ore')
	event.hide('ad_astra:deepslate_ostrum_ore')
	event.hide('ad_astra:deepslate_calorite_ore')
	event.hide('mekanism:deepslate_uranium_ore')
	event.hide('mekanism:deepslate_fluorite_ore')
	event.hide('mekanismaaa:glacio_fluorite_ore')
	event.hide('mekanismaaa:glacio_lead_ore')
	event.hide('mekanismaaa:glacio_osmium_ore')
	event.hide('mekanismaaa:glacio_uranium_ore')
	event.hide('mekanismaaa:glacio_tin_ore')
	event.hide('mekanismaaa:mars_fluorite_ore')
	event.hide('mekanismaaa:mars_uranium_ore')
	event.hide('mekanismaaa:mars_tin_ore')
	event.hide('mekanismaaa:mercury_lead_ore')
	event.hide('mekanismaaa:mercury_osmium_ore')
	event.hide('mekanismaaa:mercury_uranium_ore')
	event.hide('mekanismaaa:moon_tin_ore')
	event.hide('mekanismaaa:venus_fluorite_ore')
	event.hide('mekanismaaa:venus_lead_ore')
	event.hide('mekanismaaa:venus_uranium_ore')
	event.hide('thermal:deepslate_apatite_ore')
	event.hide('thermal:deepslate_cinnabar_ore')
	event.hide('thermal:deepslate_niter_ore')
	event.hide('thermal:deepslate_sulfur_ore')
	event.hide('deeperdarker:sculk_stone_redstone_ore')
	event.hide('deeperdarker:gloomslate_redstone_ore')

	event.hide('ftbquests:loot_crate_opener')

	event.hide('createsifter:andesite_mesh')
	event.hide('createsifter:custom_mesh')
	event.hide('createsifter:advanced_custom_mesh')
	event.hide('createsifter:dust')

	event.hide('createdieselgenerators:mold')

	event.hide('create_mechanical_chicken:seed_oil_bucket')

	event.hide('bigreactors:yellorium_nugget')
	event.hide('bigreactors:yellorium_bucket')

	event.hide('enderio:primitive_alloy_smelter')
	event.hide('enderio:alloy_smelter')
	event.hide('enderio:wood_gear')
	event.hide('enderio:stone_gear')
	event.hide('enderio:silicon')
	event.hide('enderio:light')
	event.hide('enderio:light_inverted')
	event.hide('enderio:powered_light')
	event.hide('enderio:powered_light_inverted')
	event.hide('enderio:powered_light_wireless')
	event.hide('enderio:powered_light_inverted_wireless')

	event.hide('ad_astra:oil_bucket')
	event.hide('ad_astra:coal_generator')
	event.hide('ad_astra:etrionic_blast_furnace')

	event.hide('thermal:sawdust')
	event.hide('thermal:sawdust_block')
	event.hide('createdieselgenerators:wood_chip')

})