JEIEvents.hideItems(event => {

	// event.hide(/.*:.*creative.*/)

	event.hide('ad_astra:deepslate_desh_ore')
	event.hide('ad_astra:deepslate_ice_shard_ore')
	event.hide('ad_astra:mars_ice_shard_ore')
	event.hide('ad_astra:glacio_ice_shard_ore')
	event.hide('ad_astra:deepslate_ostrum_ore')
	event.hide('ad_astra:deepslate_calorite_ore')
	event.hide('mekanism:deepslate_uranium_ore')
	event.hide('mekanism:deepslate_fluorite_ore')
	event.hide('mekanismaaa:glacio_fluorite_ore')
	event.hide('mekanismaaa:glacio_lead_ore')
	event.hide('mekanismaaa:glacio_osmium_ore')
	event.hide('mekanismaaa:glacio_uranium_ore')
	event.hide('mekanismaaa:glacio_tin_ore')
	event.hide('mekanismaaa:mars_fluorite_ore')
	event.hide('mekanismaaa:mars_uranium_ore')
	event.hide('mekanismaaa:mars_tin_ore')
	event.hide('mekanismaaa:mercury_lead_ore')
	event.hide('mekanismaaa:mercury_osmium_ore')
	event.hide('mekanismaaa:mercury_uranium_ore')
	event.hide('mekanismaaa:moon_tin_ore')
	event.hide('mekanismaaa:venus_fluorite_ore')
	event.hide('mekanismaaa:venus_lead_ore')
	event.hide('mekanismaaa:venus_uranium_ore')
	event.hide('thermal:deepslate_apatite_ore')
	event.hide('thermal:deepslate_cinnabar_ore')
	event.hide('thermal:deepslate_niter_ore')
	event.hide('thermal:deepslate_sulfur_ore')
	event.hide('deeperdarker:sculk_stone_redstone_ore')
	event.hide('deeperdarker:gloomslate_redstone_ore')

	event.hide('ftbquests:loot_crate_opener')

	event.hide('createsifter:andesite_mesh')
	event.hide('createsifter:custom_mesh')
	event.hide('createsifter:advanced_custom_mesh')
	event.hide('createsifter:dust')

	event.hide('createdieselgenerators:mold')

	event.hide('create_mechanical_chicken:seed_oil_bucket')

	event.hide('bigreactors:yellorium_nugget')
	event.hide('bigreactors:yellorium_bucket')

	event.hide('enderio:primitive_alloy_smelter')
	event.hide('enderio:alloy_smelter')
	event.hide('enderio:wood_gear')
	event.hide('enderio:stone_gear')
	event.hide('enderio:dark_bimetal_gear')
	event.hide('enderio:vibrant_gear')
	event.hide('enderio:energized_gear')
	event.hide('enderio:silicon')
	event.hide('enderio:light')
	event.hide('enderio:cake_base')
	event.hide('enderio:light_inverted')
	event.hide('enderio:powered_light')
	event.hide('enderio:powered_light_inverted')
	event.hide('enderio:powered_light_wireless')
	event.hide('enderio:powered_light_inverted_wireless')
	event.hide('enderio:painting_machine')
	event.hide('enderio:stirling_generator')
	event.hide('enderio:slice_and_splice')
	event.hide('enderio:soul_engine')
	event.hide('enderio:drain')
	event.hide('enderio:sag_mill')
	event.hide('enderio:glider_wing')
	event.hide('enderio:nutritious_stick')
	event.hide('enderio:plant_matter_brown')
	event.hide('enderio:plant_matter_green')
	event.hide('enderio:zombie_electrode')
	event.hide('enderio:ender_resonator')
	event.hide('enderio:skeletal_contractor')
	event.hide('enderio:guardian_diode')
	event.hide('enderio:frank_n_zombie')
	event.hide('enderio:sentient_ender')
	event.hide('enderio:clayed_glowstone')
	event.hide('enderio:z_logic_controller')
	event.hide('enderio:nethercotta')

	event.hide('enderio:conductive_alloy_grinding_ball')
	event.hide('enderio:pulsating_alloy_grinding_ball')
	event.hide('enderio:redstone_alloy_grinding_ball')
	event.hide('enderio:energetic_alloy_grinding_ball')
	event.hide('enderio:vibrant_alloy_grinding_ball')
	event.hide('enderio:copper_alloy_grinding_ball')
	event.hide('enderio:end_steel_grinding_ball')

	event.hide('ad_astra:oil_bucket')
	event.hide('ad_astra:coal_generator')
	event.hide('ad_astra:etrionic_blast_furnace')

	event.hide('thermal:sawdust')
	event.hide('thermal:sawdust_block')
	event.hide('createdieselgenerators:wood_chip')

	event.hide('thermal:tinker_bench')
	event.hide('thermal:charge_bench')
	event.hide('thermal:energy_cell')
	event.hide('thermal:fluid_cell')
	event.hide('thermal:machine_frame')
	event.hide('thermal:energy_cell_frame')
	event.hide('thermal:fluid_cell_frame')
	event.hide('thermal:redstone_servo')
	event.hide('thermal:rf_coil')
	event.hide('thermal:upgrade_augment_1')
	event.hide('thermal:upgrade_augment_2')
	event.hide('thermal:upgrade_augment_3')
	event.hide('thermal:xp_storage_augment')
	event.hide('thermal:rf_coil_augment')
	event.hide('thermal:rf_coil_storage_augment')
	event.hide('thermal:rf_coil_xfer_augment')
	event.hide('thermal:fluid_tank_augment')
	event.hide('thermal:item_filter_augment')
	event.hide('thermal:fluid_filter_augment')
	event.hide('thermal:rf_potato')
	event.hide('thermal:redprint')
	event.hide('thermal:satchel')
	event.hide('thermal:lock')
})