name: Build Standalone Installers

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller

    - name: Build executable with PyInstaller
      run: |
        pyinstaller --onefile --name AstroRiseInstaller installer.py

    - name: Prepare Artifacts for Linux
      if: runner.os == 'Linux'
      run: |
        mv dist/AstroRiseInstaller installer-linux
        echo './installer-linux "$@"' > installer.sh
        chmod +x installer.sh
        chmod +x installer-linux

    - name: Prepare Artifacts for Windows
      if: runner.os == 'Windows'
      run: |
        move dist\AstroRiseInstaller.exe installer.exe

    - name: Commit and push installers
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: "ci: Build and commit standalone installers"
        file_pattern: "installer.exe installer-linux installer.sh"
        commit_user_name: "GitHub Actions"
        commit_user_email: "actions@github.com"
        commit_author: "GitHub Actions <actions@github.com>"
